// <auto-generated />
using System;
using EStoreAdminRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EStoreAdminRepository.Migrations
{
    [DbContext(typeof(BrandRepository))]
    [Migration("20261002065857_BrandRepo")]
    partial class BrandRepo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EStoreAdminModel.Models.Brands.BrandModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f635c1ae-5275-436b-a9b5-d932b39214ee"),
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = new Guid("16e37681-dea8-481b-bfe7-311fc3c61008"),
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("842b856d-f03b-42f3-9efb-791f342b75b6"),
                            Name = "Vivo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
